# This file was generated by GoReleaser. DO NOT EDIT.
cask "beancount" do
  version "0.16.0"

  on_macos do
    on_arm do
      sha256 "dd3cd98bb9855155d9ca9663aba1b56caa801b87e820f97f35898ee6e452297e"
      url "https://github.com/robinvdvleuten/beancount/releases/download/v#{version}/beancount_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5a45147cfee53fcb1853b4fbdc9e6864d0bdf765a4228573413ea93f0d680931"
      url "https://github.com/robinvdvleuten/beancount/releases/download/v#{version}/beancount_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a1f22ec453b70435f9c8386ec150d680c1a17d7c336d181819c8c16551a0c28d"
      url "https://github.com/robinvdvleuten/beancount/releases/download/v#{version}/beancount_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7661b6c86a5b67f170d7cfbd242872cb7864d732abc11b989d8050a208eb6805"
      url "https://github.com/robinvdvleuten/beancount/releases/download/v#{version}/beancount_Linux_x86_64.tar.gz"
    end
  end

  name "beancount"
  desc "A fast, lightweight Beancount parser and formatter written in Go"
  homepage "https://github.com/robinvdvleuten/beancount"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beancount"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/beancount"]
    end
  end

  # No zap stanza required
end
