# This file was generated by GoReleaser. DO NOT EDIT.
cask "hlsdl" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "838710e0c6c2ce19dc7e521e86e62baeb00aad8216f5b099538fb6fee5ca77ff"
      url "https://github.com/robinvdvleuten/hlsdl/releases/download/v#{version}/hlsdl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1b0c50d8f51d275ad1e9ac16d367cf4e80aa24c93418da694be3e997632c8574"
      url "https://github.com/robinvdvleuten/hlsdl/releases/download/v#{version}/hlsdl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d3e1a0229fa62fc14b9c482224b6b8c454b91f8bdb46839c2249e945a82fb9d3"
      url "https://github.com/robinvdvleuten/hlsdl/releases/download/v#{version}/hlsdl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e85d293ea41ab55843c625aa03759ce5ba90019a6140639f43a786791799aa5a"
      url "https://github.com/robinvdvleuten/hlsdl/releases/download/v#{version}/hlsdl_Linux_arm64.tar.gz"
    end
  end

  name "hlsdl"
  desc "A small Go CLI for downloading HSL streams"
  homepage "https://github.com/robinvdvleuten/hlsdl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hlsdl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/hlsdl"]
    end
  end

  # No zap stanza required

end
